### ISSUE TITLE
Error while running with Python3 in Ubuntu

### ISSUE THREAD

**Issue by AbhishekPuranam** [leonov-av/vulnkbdiff#1]
python3 kb_comparison.py 

{'openvas', 'cve', 'nessus', 'mscve'}
200
openvas - 131
200
200
200
cve - 131
nessus - 131
mscve - 131
nvdcve-1.1-2020.json.zip
nvdcve-1.1-2019.json.zip
nvdcve-1.1-2018.json.zip
nvdcve-1.1-2017.json.zip
nvdcve-1.1-2016.json.zip
nvdcve-1.1-2015.json.zip
nvdcve-1.1-2014.json.zip
nvdcve-1.1-2013.json.zip
nvdcve-1.1-2012.json.zip
nvdcve-1.1-2011.json.zip
nvdcve-1.1-2010.json.zip
nvdcve-1.1-2009.json.zip
nvdcve-1.1-2008.json.zip
nvdcve-1.1-2007.json.zip
nvdcve-1.1-2006.json.zip
nvdcve-1.1-2005.json.zip
nvdcve-1.1-2004.json.zip
nvdcve-1.1-2003.json.zip
nvdcve-1.1-2002.json.zip
Processing OpenVAS data...
Processing the plugins..
Filtering the CVEs..
0
0 s
Processing NVD data...
data/nvd_feeds/.gitignore
Traceback (most recent call last):
  File "kb_comparison.py", line 235, in <module>
    update_cve_report_data_files();
  File "kb_comparison.py", line 195, in update_cve_report_data_files
    nvd_cves = get_nvd_cves_from_nvd_site()
  File "kb_comparison.py", line 93, in get_nvd_cves_from_nvd_site
    objects = get_cve_objects_dict(filenames=[file_name], ignore_rejected=True)
  File "kb_comparison.py", line 74, in get_cve_objects_dict
    archive = zipfile.ZipFile(os.path.join("data/nvd_feeds/", file_name), 'r')
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
root@db55f97c12b0:/vulnkbdiff# 
root@db55f97c12b0:/vulnkbdiff# ls
README.md  data  kb_comparison.py  vulnkbdiff.png
root@db55f97c12b0:/vulnkbdiff# cd data/
root@db55f97c12b0:/vulnkbdiff/data# ls
nessus_plugins  nvd_feeds  openvas_plugins  report_data  vulners_collections
root@db55f97c12b0:/vulnkbdiff/data# cd ..
root@db55f97c12b0:/vulnkbdiff# ls
README.md  data  kb_comparison.py  vulnkbdiff.png
root@db55f97c12b0:/vulnkbdiff# python3 kb_comparison.py 
{'mscve', 'cve', 'nessus', 'openvas'}
200
mscve - 131
200
200
200
cve - 131
nessus - 131
openvas - 131
nvdcve-1.1-2020.json.zip
nvdcve-1.1-2019.json.zip
nvdcve-1.1-2018.json.zip
nvdcve-1.1-2017.json.zip
nvdcve-1.1-2016.json.zip
nvdcve-1.1-2015.json.zip
nvdcve-1.1-2014.json.zip
nvdcve-1.1-2013.json.zip
nvdcve-1.1-2012.json.zip
nvdcve-1.1-2011.json.zip
nvdcve-1.1-2010.json.zip
nvdcve-1.1-2009.json.zip
nvdcve-1.1-2008.json.zip
nvdcve-1.1-2007.json.zip
nvdcve-1.1-2006.json.zip
nvdcve-1.1-2005.json.zip
nvdcve-1.1-2004.json.zip
nvdcve-1.1-2003.json.zip
nvdcve-1.1-2002.json.zip
Processing OpenVAS data...
Processing the plugins..
Filtering the CVEs..
0
0 s
Processing NVD data...
data/nvd_feeds/.gitignore
Traceback (most recent call last):
  File "kb_comparison.py", line 235, in <module>
    update_cve_report_data_files();
  File "kb_comparison.py", line 195, in update_cve_report_data_files
    nvd_cves = get_nvd_cves_from_nvd_site()
  File "kb_comparison.py", line 93, in get_nvd_cves_from_nvd_site
    objects = get_cve_objects_dict(filenames=[file_name], ignore_rejected=True)
  File "kb_comparison.py", line 74, in get_cve_objects_dict
    archive = zipfile.ZipFile(os.path.join("data/nvd_feeds/", file_name), 'r')
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by leonov-av** [comment]
Hello Abhishek,

I am getting Nessus CVEs from Vulners collection <https://vulners.com/stats>,
NOT from NASL plugins. This means that you will need to have your own
commercial/researcher Vulners license for this and set in api variable. If
you are interested in this please contact isox@vulners.com

With best regards,
Alexander Leonov

**Comment by AbhishekPuranam** [comment]
Looks like the issue here is unzipping the nvd zip file in python3

**Comment by leonov-av** [comment]
Most likely it's because you haven't set api_key variable for Vulners API
authentication.

With best regards,
Alexander Leonov

**Comment by AbhishekPuranam** [comment]
Could you help in updating readme.MD on pre-requisites

**Comment by AbhishekPuranam** [comment]
I am thinking of dockerising your tool, if you have already done, please share.
